[2019-11-21 12:52:56,254] [LinqHelper.py:55] [LinqHelper:db_del] [ERROR]- 请求出错：get() returned more than one BaseType -- it returned 23!
[2019-11-21 12:52:57,132] [LinqHelper.py:55] [LinqHelper:db_del] [ERROR]- 请求出错：get() returned more than one BaseType -- it returned 24!
[2019-11-21 12:52:57,745] [LinqHelper.py:55] [LinqHelper:db_del] [ERROR]- 请求出错：get() returned more than one BaseType -- it returned 25!
[2019-11-21 12:53:19,402] [LinqHelper.py:55] [LinqHelper:db_del] [ERROR]- 请求出错：get() returned more than one BaseType -- it returned 26!
[2019-11-21 12:53:19,405] [LinqHelper.py:55] [LinqHelper:db_del] [ERROR]- 请求出错：get() returned more than one BaseType -- it returned 26!
[2019-11-21 12:54:03,269] [LinqHelper.py:55] [LinqHelper:db_del] [ERROR]- 删除失败：get() returned more than one BaseType -- it returned 27!
[2019-11-21 12:54:03,271] [LinqHelper.py:55] [LinqHelper:db_del] [ERROR]- 删除失败：get() returned more than one BaseType -- it returned 27!
[2019-11-21 12:55:06,206] [LinqHelper.py:55] [LinqHelper:db_del] [ERROR]- 删除失败：get() returned more than one BaseType -- it returned 28!
[2019-11-21 12:55:06,209] [LinqHelper.py:55] [LinqHelper:db_del] [ERROR]- 删除失败：get() returned more than one BaseType -- it returned 28!
[2019-11-21 12:55:06,888] [LinqHelper.py:55] [LinqHelper:db_del] [ERROR]- 删除失败：get() returned more than one BaseType -- it returned 29!
[2019-11-21 12:55:06,891] [LinqHelper.py:55] [LinqHelper:db_del] [ERROR]- 删除失败：get() returned more than one BaseType -- it returned 29!
[2019-11-21 12:56:17,101] [LinqHelper.py:83] [LinqHelper:db_find] [ERROR]- 查找失败：get() returned more than one BaseType -- it returned 30!
[2019-11-21 12:56:17,104] [LinqHelper.py:55] [LinqHelper:db_del] [ERROR]- 删除失败：get() returned more than one BaseType -- it returned 30!
[2019-11-21 12:56:35,594] [LinqHelper.py:83] [LinqHelper:db_find] [ERROR]- 查找失败：get() returned more than one BaseType -- it returned 31!
[2019-11-21 12:56:35,596] [LinqHelper.py:83] [LinqHelper:db_find] [ERROR]- 查找失败：get() returned more than one BaseType -- it returned 31!
[2019-11-21 12:57:16,279] [LinqHelper.py:83] [LinqHelper:db_find] [ERROR]- 查找失败：get() returned more than one BaseType -- it returned 32!
[2019-11-21 12:57:17,073] [LinqHelper.py:83] [LinqHelper:db_find] [ERROR]- 查找失败：get() returned more than one BaseType -- it returned 33!
[2019-11-21 12:57:17,424] [LinqHelper.py:83] [LinqHelper:db_find] [ERROR]- 查找失败：get() returned more than one BaseType -- it returned 34!
[2019-11-21 12:57:17,758] [LinqHelper.py:83] [LinqHelper:db_find] [ERROR]- 查找失败：get() returned more than one BaseType -- it returned 35!
[2019-11-21 12:57:18,102] [LinqHelper.py:83] [LinqHelper:db_find] [ERROR]- 查找失败：get() returned more than one BaseType -- it returned 36!
[2019-11-21 13:25:47,970] [LinqHelper.py:78] [LinqHelper:db_find] [ERROR]- 查找失败：'QuerySet' object is not callable
[2019-11-21 13:25:50,259] [LinqHelper.py:78] [LinqHelper:db_find] [ERROR]- 查找失败：'QuerySet' object is not callable
[2019-11-21 13:25:50,912] [LinqHelper.py:78] [LinqHelper:db_find] [ERROR]- 查找失败：'QuerySet' object is not callable
[2019-11-21 13:25:51,461] [LinqHelper.py:78] [LinqHelper:db_find] [ERROR]- 查找失败：'QuerySet' object is not callable
[2019-11-21 13:26:15,568] [LinqHelper.py:78] [LinqHelper:db_find] [ERROR]- 查找失败：'QuerySet' object is not callable
[2019-11-21 13:27:56,306] [LinqHelper.py:79] [LinqHelper:db_find] [ERROR]- 查找失败：'QuerySet' object is not callable
[2019-11-21 13:28:22,714] [LinqHelper.py:80] [LinqHelper:db_find] [ERROR]- 查找失败：'QuerySet' object is not callable
[2019-11-21 13:28:38,419] [LinqHelper.py:80] [LinqHelper:db_find] [ERROR]- 查找失败：'QuerySet' object is not callable
[2019-11-21 13:31:44,457] [LinqHelper.py:78] [LinqHelper:db_find] [ERROR]- 查找失败：'QuerySet' object is not callable
[2019-11-21 13:31:45,442] [LinqHelper.py:78] [LinqHelper:db_find] [ERROR]- 查找失败：'QuerySet' object is not callable
[2019-11-21 13:32:23,940] [LinqHelper.py:78] [LinqHelper:db_find] [ERROR]- 查找失败：'QuerySet' object is not callable
[2019-11-21 13:32:24,703] [LinqHelper.py:78] [LinqHelper:db_find] [ERROR]- 查找失败：'QuerySet' object is not callable
[2019-11-21 13:32:42,068] [LinqHelper.py:78] [LinqHelper:db_find] [ERROR]- 查找失败：'QuerySet' object is not callable
[2019-11-21 13:34:34,279] [LinqHelper.py:78] [LinqHelper:db_find] [ERROR]- 查找失败：'QuerySet' object is not callable
[2019-11-21 13:34:37,218] [LinqHelper.py:78] [LinqHelper:db_find] [ERROR]- 查找失败：'QuerySet' object is not callable
[2019-11-21 13:34:37,636] [LinqHelper.py:78] [LinqHelper:db_find] [ERROR]- 查找失败：'QuerySet' object is not callable
[2019-11-21 13:34:39,471] [LinqHelper.py:78] [LinqHelper:db_find] [ERROR]- 查找失败：'QuerySet' object is not callable
[2019-11-21 13:34:39,973] [LinqHelper.py:78] [LinqHelper:db_find] [ERROR]- 查找失败：'QuerySet' object is not callable
[2019-11-21 13:34:56,141] [LinqHelper.py:78] [LinqHelper:db_find] [ERROR]- 查找失败：'QuerySet' object is not callable
[2019-11-21 13:35:35,304] [LinqHelper.py:78] [LinqHelper:db_find] [ERROR]- 查找失败：'QuerySet' object is not callable
[2019-11-21 19:32:27,473] [LinqHelper.py:77] [LinqHelper:db_find] [ERROR]- 查找失败：invalid literal for int() with base 10: 'undefined'
